name: MySQL and Golang Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          # The MySQL docker container requires these environment variables to be set
          # so we can create and migrate the test database.
          # See: https://hub.docker.com/_/mysql
          MYSQL_DATABASE: cloud_data
          MYSQL_ROOT_PASSWORD: 'vcoder'
        ports:
          # Opens port 3306 on service container and host
          # https://docs.github.com/en/actions/using-containerized-services/about-service-containers
          - 3306:3306
          # Before continuing, verify the mysql container is reachable from the ubuntu host
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.21.5'
      - run: go version
      - name: Create DB structure
        run: |
          sudo mysql -h 127.0.0.1 -u root -pvcoder cloud_data < domains.sql

      - name: Build and run Golang code
        run: |
          go build -o myapp
          ./myapp

      - name: Export MySQL data
        run: sudo mysql -h 127.0.0.1 -u root -pvcoder cloud_data > exported_data.sql

      - name: Commit and push changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"

          git add exported_data.sql
          git commit -m "Exported MySQL data"
          git push origin main
