name: MySQL and Golang Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
          image: mysql:8.0
          env:
              MYSQL_DATABASE: cloud_data
              MYSQL_USER: root
              MYSQL_PASSWORD: ''
              MYSQL_ROOT_PASSWORD: ''
          ports:
              - 3306
          options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5


    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create DB structure
        run: |
          sudo /lib/systemd/systemd-sysv-install enable mysql
          sudo systemctl enable mysql.service
          sudo systemctl start mysql.service
          sudo systemctl status mysql.service
          sudo mysql -h 127.0.0.1 -u root cloud_data < domains.sql

      - name: Build and run Golang code
        run: |
          go build -o myapp
          ./myapp

      - name: Export MySQL data
        run: sudo mysql -h 127.0.0.1 -u root cloud_data > exported_data.sql

      - name: Commit and push changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"

          git add exported_data.sql
          git commit -m "Exported MySQL data"
          git push origin main
